name: toc-generator

on:
  push:
    branches:
      - develop
  
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - name: toc-generator
        uses: technote-space/toc-generator@v3
        with:
          FOLDING: true
          TOC_TITLE: "**目次**"
          TARGET_PATHS: "**/*.md"
          