name: toc-generator

on:
  push:
    branches:
      - develop
  
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: workflow-settings.json
      - name: toc-generator
        uses: technote-space/toc-generator@v3
        with:
          FOLDING: ${{ env.TOC.FOLDING}}
          TOC_TITLE: ${{ env.TOC.TITLE }}
          TARGET_PATHS: ${{ env.TOC.TARGET_PATHS }}
          COMMIT_MESSAGE: ${{ env.TOC.COMMIT_MESSAGE }}

  slack-notify:
    if: always()
    needs: [generateTOC]
    name: workflow notification to slack
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: workflow-settings.json
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          name: 'Github Actions Workflow'
          channel: '#random'
          icon_url: 'https://user-images.githubusercontent.com/47489629/104346721-16e1d200-5543-11eb-869f-80ac22ee4501.png'
          