# This is a basic workflow to help you get started with Actions

name: toc-generate

on:
  push:
   - main
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
