name: toc-generate

on: 
  push:
    branches:
      - develop

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v3
        with:
          TOC_TITLE: "**目次**"
          COMMIT_MESSAGE: "#1 Add: 目次作成"
          TARGET_PATHS: *.md